### PR TITLE
feat: add prop children in cell component

### PR DESCRIPTION
**Pull request by brunohkbx**
# Why?
It would be nice to be able to render additional components in the cell. Such as an inline picker, DateTime, and so on.

This lib `Eureka` in Swift has some cool examples of cells using inline components
https://github.com/xmartlabs/Eureka/blob/master/Example/Media/RowGifs/EurekaDateInlineRow.gif
https://github.com/xmartlabs/Eureka/blob/master/Example/Media/RowGifs/EurekaDateTimeInlineRow.gif

uL5K7PUk

### CODE REVIEW

**Comment by Purii** [comment]
Makes sense! I will look into that :)

**Comment by Purii** [comment]
Hi @brunohkbx!
Thanks for you work! Seems like a good addition with a solid api.

Was unsure about the separate style element `cellBackgroundColor`, but it makes sense.

One point. Is there any other alternative to the picker component we could use which is already included in react native core?
Otherwise I suggest to migrate to `@react-native-community/picker` in the example to be prepared for future core updates (currently there's just a warning)

**Comment by brunohkbx** [comment]
> Was unsure about the separate style element cellBackgroundColor, but it makes sense.

I had to extract this in order to reuse it in both `renderCell` and `renderCellWithSafeAreaView`

>  Is there any other alternative to the picker component we could use which is already included in react native core?
My bad. I totally forgot that `Picker` was deprecated. Unfortunately, I don't have a MacOS to do this [extra step](https://github.com/react-native-picker/picker#macos)

**Comment by brunohkbx** [comment]
I got the updated `Podfile.lock` from a friend :sweat_smile: . I think it's good now.

**Comment by Purii** [comment]
Release with `v4.3.0`. Thanks for your work @brunohkbx! 🚀

**Pull request merged**
