### PR TITLE
Added functionality to set text styles on cell titles.  

### PR DESCRIPTION
**Pull request by beaurushton**
This allows setting the font and size of text etc in the cell title.

### CODE REVIEW

**Comment by Purii** [comment]
Thank you, @beaurushton!
Could you please fix the checks?

**Comment by sibelius** [comment]
@beaurushton could u please rebase ur work?

**Comment by Purii** [comment]
In my opinion it wouldn't be that helpful to make every single aspect modifiable through props.

Have you considered something like the following?
Additionally you could write a wrapper component.

```javascript
<Cell
 cellContentView={
  <View
    style={{ alignItems: 'center', flexDirection: 'row', flex: 1, paddingVertical: 10 }}
  >
   <Text
    allowFontScaling
    numberOfLines={1}
    style={{ flex: 1, fontSize: 20 }}
   >
    Title
   </Text>
  </View>
 }
/>
```

**Comment by beaurushton** [comment]
I'd say using a custom font is a fairly common use case for most apps, this approach adds that option plus more flexibility.

**Comment by beaurushton** [comment]
Checks seem to be failing as the tests are no longer valid

**Comment by Purii** [comment]
The new props are `detailTextStyle`, `titleTextStyle` and `titleTextStyleDisabled`.

**Pull request merged**
