### PR TITLE
Adds conditional separator for stand alone Cell and new Cell type: 'RightDetailSubtitle'

### PR DESCRIPTION
**Pull request by Mindaugas-Jacionis**
Adds:
- separator and separatorStyle props for Cell. These are useful when Cell is used alone without Section, or is wrapped in additional component, therefore separator from Section is not drawn
- RightDetailSubtitle Cell type, to be able to have subtitle and right detail at the same time
- Updated Readme.md to include the changes

### CODE REVIEW

**Comment by Mindaugas-Jacionis** [comment]
@Purii - will you review? :)

**Comment by inlinecoder** [comment]
@Mindaugas-Jacionis can you add a screenshot, please?

**Comment by Purii** [comment]
@Mindaugas-Jacionis When do you use multiple cells without a section? That's what a section is for. It would be possible to allow configuring the paddings of a section. Would that help you?

**Comment by Mindaugas-Jacionis** [comment]
@inlinecoder I've added a screenshot here of the case when I use this new cell
screen shot 2017-06-02 at 2 04 01 pm

@Purii in the screenshot you can see this section 'Price details'. These price details are made as a component that I am also using in another screen where I add this component to bigger section with more cells and that's when I loose all the separators of cells and I have a need to use cells as stand alone components.

**Comment by Purii** [comment]
@Mindaugas-Jacionis Understood. Unfortunately it is not that easy to add separators to the cell component. For example will the separators need to be hidden while the cell is highlighted (already had considered moving the section to the cell while implementing this. Result was that it would not have been a proper solution). Most important I want to keep the components api clean and the implementation good to understand.

### Better way?
Have you considered changing your `Price Details` component?

```javascript
## PriceDetails Component(s)
export const PriceDetailsCells = () => .....
export const PriceDetailsCellsWithSection = () => <Section.....><PriceDetailsCells /></Section>

## other file
import { PriceDetailsCells, PriceDetailsCellsWithSection } from ...
```
Is that a solution you would accept?

## Cell Type `RightDetailSubtitle`
Looks good, thank you! I will gladly merge it. Could you please separate it from the separator topic?

**Pull request closed without merging**
