### PR TITLE
feat(tableview): add style prop to tableview wrapper

### LINKED ISSUE #314: Not possible to use themes with FlatList
The example of `FlatList` usage in README uses only the `Cell` component, without wrapping it `TableView`, this causes the custom appearances and themes to stop working within the Cell component. 

```tsx
      <FlatList
        data={activities}
        renderItem={({ item, separators }) => <Cell title={item.text} />}
      />
```

image

Should there be a way to style `TableView` so it can be used as a general wrapper? Maybe something like this:

```tsx
    <TableView style={{ flex: 1 }}>
      <FlatList
        data={activities}
        renderItem={({ item, separators }) => <Cell title={item.text} />}
      />
    </TableView>
```

Sent a PR that fixes this.

### PR DESCRIPTION
**Pull request by sallar**
Fixes #314

### CODE REVIEW

**Comment by Purii** [comment]
Looks good. Thanks a lot @sallar!

**Comment by sallar** [comment]
Thanks @Purii for merging it. Can have a release soon by any chance?

**Comment by Purii** [comment]
Will cut a release soon. But there are some issue with the types I want to fix first. Seems to be introduced by a recent version of `@types/react-native`

**Comment by Purii** [comment]
@sallar released as [`4.2.0`](https://github.com/Purii/react-native-tableview-simple/blob/master/CHANGELOG.md#420-2020-09-09)

**Pull request merged**
